---
# Use %KEY-NAME% in this file and it will be replaced with the value of
# $GLOBALS['KEY-NAME'] if it exists. If the key name does not exist, this script
# won't work (Need to build in proper error handling @TODO RD 2017-05-16
#
# Example usage:
#assets: Top-level key name
#    asset-short-name: Short name
#        basePath: %assets_static_relative%/full/path/to/deepest/common/file
#        script: null filename or null
#        link: jquery-ui.min.css filename or null
assets:
    jquery-ui-darkness:
        basePath: %assets_static_relative%/jquery-ui-1-12-1/themes/ui-darkness/
        link: jquery-ui.min.css
    datetimepicker:
        basePath: %assets_static_relative%/jquery-datetimepicker-2-5-4/build/
        script: jquery.datetimepicker.full.min.js
        link: jquery.datetimepicker.min.css
    jquery-ui:
        basePath: %assets_static_relative%/jquery-ui-1-12-1/
        script: jquery-ui.min.js
    report_helper:
        basePath: %webroot%/library/js/
        script: report_helper.js
assets_autoload:
    jquery:
        basePath: %assets_static_relative%/jquery-3-1-1/
        script: index.js
    bootstrap:
        basePath: %assets_static_relative%/bootstrap-3-3-4/dist
        script: js/bootstrap.min.js
        link: css/bootstrap.min.css
    fontawesome:
        basePath: %assets_static_relative%/font-awesome-4-6-3/css/
        link: font-awesome.min.css
    textformat:
        basePath: %webroot%/library
        script: textformat.js
    dialog:
        basePath: %webroot%/library
        script: dialog.js
